# Random Forest Configuration
random_forest:
  n_estimators: 200
  max_depth: 15
  min_samples_split: 5
  min_samples_leaf: 2
  class_weight: "balanced"
  random_state: 42
  n_jobs: -1

# Gradient Boosting Configuration
gradient_boosting:
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 6
  min_samples_split: 5
  min_samples_leaf: 2
  random_state: 42

# Logistic Regression Configuration
logistic_regression:
  class_weight: "balanced"
  max_iter: 1000
  random_state: 42
  n_jobs: -1
  solver: "lbfgs"

# Neural Network Configuration
neural_network:
  hidden_layer_sizes: [100, 50, 25]
  activation: "relu"
  solver: "adam"
  alpha: 0.0001
  batch_size: "auto"
  learning_rate: "adaptive"
  learning_rate_init: 0.001
  max_iter: 500
  early_stopping: true
  validation_fraction: 0.1
  random_state: 42

# Isolation Forest Configuration (Unsupervised)
isolation_forest:
  contamination: 0.1
  n_estimators: 100
  max_samples: "auto"
  random_state: 42
  n_jobs: -1

# Hybrid Ensemble Configuration
hybrid_ensemble:
  use_supervised_voting: true
  use_unsupervised_anomaly: true
  voting_strategy: "soft"  # Options: hard, soft
  unsupervised_weight: 0.3
  supervised_weight: 0.7
